{
    'name': 'Employee Accommodation Management',
    'version': '15.0.1.0.0',
    'category': 'Accommodation Management',
    'summary': 'Manage employee accommodations in camps, rooms, and beds',
    'icon': '/employee_accommodation/static/description/icon.png',
    'depends': ['base','hr','contacts','hr_extended','hr_resignation','mail', 'report_xlsx'],
    'data': [
        "security/ir.model.access.csv",
        "security/security.xml",
        "data/employee_accommodation_sequence.xml",
        "data/client_accommodation_sequence.xml",
        "data/camp_seq.xml",
        "data/tenancy_contract.xml",
        "wizard/bed_reservation_wizard_view.xml",
        "wizard/customer_onboarding_views.xml",
        # "reports/report.xml",
        # "reports/camp_details_template.xml",
        "reports/customer_lease_report.xml",
        "reports/header_template.xml",
        "reports/occupancy_report_template.xml",
        "reports/available_beds_report_template.xml",
        "reports/available_room_report_template.xml",
        "reports/employee_occupancy_template.xml",
        "reports/summary_report_template.xml",
        "reports/occupancy_excel_report_views.xml",
        "reports/available_beds_excel_report.xml",
        "reports/available_room_excel_report_views.xml",
        "views/camp_views.xml",
        "views/floor_views.xml",
        "views/room_views.xml",
        "views/bed_views.xml",
        "views/facility_views.xml",
        "views/check_in_views.xml",
        "views/check_out_views.xml",
        "views/check_list_views.xml",
        "views/employee_transfer_views.xml",
        "views/client_accommodation_views.xml",
        "views/hr_employee_views.xml",
        "views/employee_fine_views.xml",
        "views/customer_checkin_views.xml",
        "views/customer_checklist_views.xml",
        "views/customer_checkout_views.xml",
        "views/menu.xml",
        "wizard/occupancy_report_wizard_view.xml",
        "wizard/available_beds_wizard_view.xml",
        "wizard/available_room_wizard_view.xml",
        "wizard/summary_report_wizard_views.xml",
        "wizard/occupancy_excel_wizard_views.xml",
        "wizard/available_beds_excel_wizard.xml",
        "wizard/available_room_excel_wizard_views.xml",
    ],
    'installable': True,
    'application': True,
}