{
    'name': 'Payroll Reports',
    'summary': "Hr Payroll Report",
    'description': "Payroll Reports",
    'category': 'Payslip',
    'version': '15.0.1.0',
    'author': 'Olive Infocraft Trading LLC',
    'depends': ['base','hr', 'base','sale','hr_payroll','report_xlsx','hr_contract','branch','hr_payroll_account','hr_payroll_extended','hr_extended','account','account_extended','account_accountant','hr_work_entry_contract_enterprise','sale_extended', 'budget_customizations'],
    'data': [
        'security/ir.model.access.csv',
        'security/hr_contract_report_security.xml',
        'reports/report_template.xml',
        'reports/contract_report_template.xml',
        'reports/employee_billing_report.xml',
        'reports/employee_billing_summary_report.xml',
        'reports/billing_payroll_comparison_report.xml',
        'reports/sales_register_report.xml',
        'reports/new_customer_revenue_report.xml',
        'reports/unbilled_revenue_report.xml',
        'reports/payment_report.xml',
        'reports/payment_voucher_report.xml',
        'reports/acp_report.xml',
        'reports/dpo_report.xml',
        'reports/acp_working_report.xml',
        'reports/dpo_working_report.xml',
        'reports/pl_report.xml',
        'reports/bs_report.xml',
        'reports/cost_plus_report.xml',
        'views/hr_payslip.xml',
        'views/res_partner.xml',
        'views/pl_bs_group_view.xml',
        'views/account_account_view.xml',
        'views/menu.xml',
        'wizard/payroll_wizard_views.xml',
        'wizard/contract_wizard_views.xml',
        'wizard/employee_billing.xml',
        'wizard/employee_billing_summary_report_wizard.xml',
        'wizard/billing_payroll_comparison_report_wizard.xml',
        'wizard/sales_register_wizard_views.xml',
        'wizard/new_customer_revenue_wizard_views.xml',
        'wizard/unbilled_revenue_wizard_views.xml',
        'wizard/leave_pay_journal_wizard.xml',
        'wizard/acp_report_wizard_view.xml',
        'wizard/dpo_report_wizard_view.xml',
        'wizard/acp_working_wizard_view.xml',
        'wizard/dpo_working_wizard_view.xml',
        'wizard/pl_report_wizard_view.xml',
        'wizard/bs_report_wizard_view.xml',
        'wizard/cost_plus_report_wizard_view.xml',
    ],

    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
