{
    'name': "Visa",
    'summary': "Visa Processing",
    'description': "Visa Process",
    'category': 'operation',
    'version': '15.0.0',
    'author':'Olive Infocraft',
    'website': "http://www.dishicreation.com",
    'icon': '/visa_processing/static/description/icon.png',
    'depends': ['hr_recruitment','mail','hr_extended','base', 'contacts', 'report_xlsx', 'hr_recruitment_reports', 'branch','hr','hr_request_portal', 'hr_contract','hr_payroll', 'hr_work_entry_contract_enterprise'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/sequence.xml',
        "reports/visa_request_report_template.xml",
        'reports/visa_quota_report.xml',
        'reports/manpower_requisition_report.xml',
        'views/manpower_requisition_views.xml',
        'views/hr_applicant_views.xml',
        'views/visa_quota_views.xml',
        'views/visa_request_application_views.xml',
        'views/menu_views.xml',
        "wizard/visa_request_report_wizard_view.xml",
        "wizard/visa_quota_wizard_views.xml",
        "wizard/visa_request_excel_wizard.xml",
        "wizard/manpower_requisition_wizard.xml",
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}