# -*- coding: utf-8 -*-
{
    'name': "Sale Extended",
    'summary': "Sale Extended",
    'description': "Sale Extended",
    'category': 'Sale',
    'version': '15.0.0',
    'author':'Preciseways',
    'website': "http://www.preciseways.com",
    'depends': ['base', 'project','project_extended','sale_crm','resource','sale_management', 'uom', 'hr_extended',
     'crm','branch_extended','bi_odoo_crm_multi_branch','hr_skills', 'account_fleet','pways_terms_condition','peoplesol_other_earnings'],
    'data': [
        'security/groups.xml',
        'security/rule.xml',
        'security/ir.model.access.csv',
        # 'data/cron.xml',
        'data/data.xml',
        'data/group.xml',
        'data/mail_template.xml',
        'wizard/customer_approve_view.xml',
        'wizard/trader_task.xml',
        'views/cost_plus_view.xml',
        'views/site_frequency.xml',
        'views/customer_master.xml',
        'views/customer_onboarding_request.xml',
        'views/supplier_onboarding_request.xml',
        'views/res_partner_view.xml',
        'views/sale_order.xml',
        'views/crm_extended.xml',
        'views/account_move_view.xml',
        'views/sale_agreement.xml',
        'views/site_visit.xml',
        'views/sale_site_inspection_view.xml',
        'views/project_task_view.xml',
        'views/hr_employee.xml',
        'views/actual_attendance_view.xml',
        'views/other_earnings_views.xml',
        'report/report_actions.xml',
        'report/sale_template.xml',
        'report/sale_quotation_report.xml',

    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
