# -*- coding: utf-8 -*-
{
    'name': "Gt Helpdesk Extended",
    'summary': "helpdesk extended",
    'category': 'HR',
    'version': '15.0.0',
    'author': 'Dishicreation',
    'depends': ['helpdesk', 'helpdesk_extended','branch','hr'],
    'data': [
        'security/ir.model.access.csv',
        'data/inherit_mail_template.xml',
        'data/initial_complaint_response.xml',
        'data/opening_email_template.xml',
        'data/closing_ticket_corrective.xml',
        'data/closing_ticket_preventive.xml',
        'data/closing_ticket_resolution.xml',
        'data/corrective_preventive_ticket.xml',
        'data/corrective_resolution_ticket.xml',
        'data/preventive_resolution_ticket.xml',
        'data/email_template.xml',
        'data/helpdesk_escalation.xml',
        'data/closing_tickets.xml',
        'views/helpdsk_extended_view.xml',
        'views/helpdesk_sla.xml',
        'wizard/quotation_mail_template.xml',
        'wizard/assign_or_reassign_view.xml',
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
