# -*- coding: utf-8 -*-
from . import customer_onboarding_request
from . import customer_master
from . import res_partner
from . import supplier_onboarding_request
from . import sale_order
from . import crm_extended
from . import account_move
from . import sale_agreement
from . import site_visit
from . import sale_site_inspection
from . import project_task
from . import sale_advance_payment
from . import mail_activity
from . import actual_attendance
from . import cost_plus
from . import sale_advance_payment_inv
from . import other_earnings
from . import planning_slot
