# -*- coding: utf-8 -*-
{
    'name': "Account Extended",
    'summary': "Account Extended",
    'description': "Account Extended",
    'category': 'Project',
    'author': 'Preciseways',
    'version': '15.0.0',
    'depends': ['account', 'account_accountant', 'account_asset', 'hr', 'maintenance', 'sale_extended', 'pways_terms_condition', 'account_check_printing', 'account_fleet', 'account_auto_transfer', 'branch'],
    'data': [
        'security/ir.model.access.csv',
        'views/asset_location_view.xml',
        'views/asset_sub_location_view.xml',
        'views/asset_classification_view.xml',
        'views/account_asset_view.xml',
        'views/maintenance_equipment_view.xml',
        'views/account_journal_view.xml',
        'views/account_move_view.xml',
        'views/transfer_model_view.xml',
        'views/transfer_template_view.xml',
        'views/unit_type_view.xml',
        'report/report_action.xml',
        'report/customer_report.xml',
        'report/ver2_report.xml',
        'wizard/receive_date_wizard.xml',
        'data/account_asset_seq.xml',
        'report/report_actions.xml',
        'report/account_move_template.xml',
        'wizard/statement_of_account_wizard.xml',
        'wizard/statement_of_account_ver2_wizard.xml',
        'views/account_payment_view.xml',
        'report/invoice_dulsco_report.xml',
        'report/invoice_acknowledgement_report.xml',
    ],
    'assets': {
        'web.assets_qweb': [
            'account_extended/static/src/xml/*',
        ],
    },
    'license': 'LGPL-3',
}
