# -*- coding: utf-8 -*-
{
    'name': "Project Extended",
    'summary': "Project Extended",
    'description': "Project Extended",
    'category': 'Project',
    'version': '15.0.0',
    'author': 'Preciseways',
    'website': "http://www.preciseways.com",
    'depends': ['hr_holidays', 'sale_project', 'resource', 'branch', 'stock', 'maintenance', 'fleet', 'planning',
                'pways_hr_shift_allocation', 'hr_attendance', 'hr_timesheet', 'hr_overtime_automatic',
                'project_forecast', 'project_enterprise', 'contacts_extended'],
    'data': [
        'security/ir.model.access.csv',
        'data/project_task_seq.xml',
        'reports/report_idle_timesheet.xml',
        'wizard/lpo_control_wizard_view.xml',
        # 'wizard/warning_check_stop_view.xml',
        'wizard/idle_timesheet.xml',
        'wizard/project_shift_wizard.xml',
        'wizard/employee_task_bulk_reported_view.xml',
        'views/project_view.xml',
        'views/lpo_control_view.xml',
        'views/sale_order_view.xml',
        'views/maintenance_equipment_view.xml',
        'views/planning_view.xml',
        'wizard/task_invoice_wizard_view.xml',
        'views/product_view.xml',
        'views/employee_avilable.xml',
        'views/employee_schedule.xml',
        'views/stop_warning.xml',
        'views/account_analytic_line.xml',
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
